In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv("ratings_Electronics (1).csv")
print(data.head())

    AKM1MP6P0OYPR  0132793040  5.0  1365811200
0  A2CX7LUOHB2NDG  0321732944  5.0  1341100800
1  A2NWSAGRHCP8N5  0439886341  1.0  1367193600
2  A2WNBOD3WNDNKT  0439886341  3.0  1374451200
3  A1GI0U4ZRJA8WN  0439886341  1.0  1334707200
4  A1QGNMC6O1VW39  0511189877  5.0  1397433600

In [2]:
data.columns = ['user_id', 'product_id','ratings','timestamp']
df = data[:int(len(data) * .1)]

In [3]:
df

               user_id  product_id  ratings   timestamp
0       A2CX7LUOHB2NDG  0321732944      5.0  1341100800
1       A2NWSAGRHCP8N5  0439886341      1.0  1367193600
2       A2WNBOD3WNDNKT  0439886341      3.0  1374451200
3       A1GI0U4ZRJA8WN  0439886341      1.0  1334707200
4       A1QGNMC6O1VW39  0511189877      5.0  1397433600
...                ...         ...      ...         ...
782443   AJCTX83JGN5TA  B000BUEGX6      1.0  1174780800
782444  A304060TQDNUBW  B000BUEGX6      5.0  1234569600
782445  A203POZSD29MKE  B000BUEGX6      5.0  1189036800
782446   AC370JXLYIWUN  B000BUEGX6      5.0  1241395200
782447   AY5IAT0TP4OAW  B000BUEGX6      5.0  1162857600

[782448 rows x 4 columns]

In [4]:
df.isnull().sum()

user_id       0
product_id    0
ratings       0
timestamp     0
dtype: int64

In [5]:
counts = df['user_id'].value_counts()
counts

A5JLAU2ARJ0BO     384
A231WM2Z2JL0U3    249
A25HBO5V8S8SEA    163
A6FIAB28IS79      113
AT6CZDCP4TRGA     112
                 ...
AYK3XA6M9FGSC       1
AQ1OMXIN4TQ0H       1
A2M4KVAS2J9O3C      1
AAQBM3POZKT9H       1
AY5IAT0TP4OAW       1
Name: user_id, Length: 606149, dtype: int64

In [6]:
data = df[df['user_id'].isin(counts[counts >= 50].index)]

In [7]:
data

               user_id  product_id  ratings   timestamp
2161     A5JLAU2ARJ0BO  1400532655      1.0  1291334400
7380    A2AEZQ3DGBBLPR  B000000O48      5.0  1038873600
7447    A2R6RA8FRBS608  B000001OL6      4.0  1209513600
7788    A11D1KHM7DVOQK  B000001OMN      2.0  1167350400
8731      A6FIAB28IS79  B00000J05A      3.0   985564800
...                ...         ...      ...         ...
778202  A3OXHLG6DIBRW8  B000BSOBG0      4.0  1267315200
779340   AKT8TGIT6VVZ5  B000BTFZZA      5.0  1147737600
780931  A149RNR5RH19YY  B000BTL0OA      5.0  1141689600
781739   A1RPTVW5VEOSI  B000BTPVHW      3.0  1172102400
781825  A3OXHLG6DIBRW8  B000BTQXUG      4.0  1272240000

[2550 rows x 4 columns]

In [9]:
data.groupby('product_id')['ratings'].mean().sort_values(ascending=False)

product_id
B000068IGI    5.0
B00006IJO4    5.0
B00006JI6T    5.0
B0001CNKCM    5.0
B000816XI4    5.0
             ...
B00005QWZ7    1.0
B00009W5QR    1.0
B00005RKO5    1.0
B00005UV2R    1.0
1400532655    1.0
Name: ratings, Length: 2207, dtype: float64

In [11]:
final_ratings = data.pivot(index = 'user_id', columns ='product_id', values = 'ratings').fillna(0)
final_ratings

product_id,1400532655,B000000O48,B000001OL6,B000001OMN,B00000J05A,B00000J061,B00000J0E8,B00000J1E6,B00000J1EP,B00000J1G6,...,B000BQ57BU,B000BQ7GW8,B000BQVYIA,B000BSLTIS,B000BSLTMY,B000BSOBG0,B000BTFZZA,B000BTL0OA,B000BTPVHW,B000BTQXUG
user_id,,,,,,,,,,,,,,,,,,,,,
A11D1KHM7DVOQK,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A12DLJESJKM1OQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A149RNR5RH19YY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0
A1F9Z42CFF9IAY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A1FR68QH6Z4YZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A1JWSDDIH5Z7DV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A1MJMYLRTZ76ZX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A1RPTVW5VEOSI,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
A203OCQQ12MAVT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A231WM2Z2JL0U3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A25HBO5V8S8SEA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A2AEZQ3DGBBLPR,0.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A2AY4YUOX2N1BQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A2B7BUH8834Y6M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A2BGZ52M908MJY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A2CL818RN52NWN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A2R6RA8FRBS608,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
A3OXHLG6DIBRW8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,4.0,0.0,4.0,0.0,0.0,0.0,4.0
A5JLAU2ARJ0BO,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A6FIAB28IS79,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A7Y6AVS576M03,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ABH9D1TEOJ56E,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AGHZXQL9F94T9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AGXV8E7XK9J6H,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AKT8TGIT6VVZ5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
AT2J7H5TRZM8Z,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AT6CZDCP4TRGA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
num_of_ratings = np.count_nonzero(final_ratings)
num_of_ratings

2550

In [16]:
possible_ratings = final_ratings.shape[0] * final_ratings.shape[1]
possible_ratings

59589

In [18]:
density = (num_of_ratings/possible_ratings)
density

0.042793132960781355

In [19]:
density *= 100
final_ratings_T = final_ratings.transpose()

In [21]:
grouped = data.groupby('product_id').agg({'user_id': 'count'}).reset_index()
grouped

      product_id  user_id
0     1400532655        1
1     B000000O48        1
2     B000001OL6        1
3     B000001OMN        1
4     B00000J05A        1
...          ...      ...
2202  B000BSOBG0        1
2203  B000BTFZZA        1
2204  B000BTL0OA        1
2205  B000BTPVHW        1
2206  B000BTQXUG        1

[2207 rows x 2 columns]

In [22]:
grouped.rename(columns = {'user_id': 'score'},inplace=True)

In [23]:
grouped

      product_id  score
0     1400532655      1
1     B000000O48      1
2     B000001OL6      1
3     B000001OMN      1
4     B00000J05A      1
...          ...    ...
2202  B000BSOBG0      1
2203  B000BTFZZA      1
2204  B000BTL0OA      1
2205  B000BTPVHW      1
2206  B000BTQXUG      1

[2207 rows x 2 columns]

In [24]:
training_data = grouped.sort_values(['score', 'product_id'], ascending = [0,1])

In [25]:
training_data

      product_id  score
113   B00004SB92      6
1099  B00008OE6I      5
368   B00005AW1H      4
612   B0000645C9      4
976   B00007KDVI      4
...          ...    ...
2202  B000BSOBG0      1
2203  B000BTFZZA      1
2204  B000BTL0OA      1
2205  B000BTPVHW      1
2206  B000BTQXUG      1

[2207 rows x 2 columns]

In [26]:
training_data['Rank'] = training_data['score'].rank(ascending=0, method='first')

In [27]:
training_data

      product_id  score    Rank
113   B00004SB92      6     1.0
1099  B00008OE6I      5     2.0
368   B00005AW1H      4     3.0
612   B0000645C9      4     4.0
976   B00007KDVI      4     5.0
...          ...    ...     ...
2202  B000BSOBG0      1  2203.0
2203  B000BTFZZA      1  2204.0
2204  B000BTL0OA      1  2205.0
2205  B000BTPVHW      1  2206.0
2206  B000BTQXUG      1  2207.0

[2207 rows x 3 columns]

In [28]:
recommendations = training_data.head()

In [30]:
def recommend(id):     
    recommend_products = recommendations 
    recommend_products['user_id'] = id 
    column = recommend_products.columns.tolist() 
    column = column[-1:] + column[:-1] 
    recommend_products = recommend_products[column] 
    return recommend_products 

print(recommend(12))

      user_id  product_id  score  Rank
113        12  B00004SB92      6   1.0
1099       12  B00008OE6I      5   2.0
368        12  B00005AW1H      4   3.0
612        12  B0000645C9      4   4.0
976        12  B00007KDVI      4   5.0

C:\Users\33255751\AppData\Local\Temp\ipykernel_13876\2320707647.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recommend_products['user_id'] = id